### ISSUE TITLE
[1.0.3] Restarting level with bike keeps bike

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#85] opened 2017-02-04 16:38 UTC
Submitter: Technidecimal
If you obtain the bike as Carol (well, obviously) and restart the level, you will be brought back to the start of the level with the bike. If the in-game timer didn't reset when you restarted the level, this would be fine. However, since it does, doing this trick can cause faster records than should be possible. I don't believe this was intentional, but I apologize if it was.

**Comment by Abel9210** [comment] 2017-02-04 19:59
This is a duplicate of an issue. Has yet to be addressed by Strife, but closing this anyway.

https://github.com/neonobjclash/fp2bugs/issues/61

**Closed as completed by Abel9210** 2017-02-04 19:59 UTC
Labels: duplicate
