### ISSUE TITLE
Boss Battle Start Trigger Location

### ISSUE THREAD

**Issue by calebj** [GalaxyTrail/fp2bugs#84] opened 2017-02-04 13:12 UTC
Submitter: Lopson
On 1.0.3, I can only get the boss battle to start by standing close to the middle of the boss battle arena. Dunno if it's intentional.

**Comment by Abel9210** [comment] 2017-02-04 19:54
This is a duplicate of an issue that has been addressed by Strife. Will be fixed in the next patch.

https://github.com/neonobjclash/fp2bugs/issues/30

**Closed as completed by Abel9210** 2017-02-04 19:54 UTC
Labels: duplicate
